# coding: utf8
# print u'你'.encode('utf-8')
import random
# Chapter 1: Vocabulary
# Page 21
words = [
    {'character': u'你',     'pinyin': u'nǐ',            'type': 'pronoun',            'translation': 'you' },                                
    {'character': u'好',     'pinyin': u'hǎo',           'type': 'adjective',            'translation': 'fine; good; nice; O.K.; it’s settled' },                            
    {'character': u'请',     'pinyin': u'qǐng',          'type': 'verb',            'translation': 'please (polite form of request); to treat or to invite (somebody)'},
    {'character': u'问',     'pinyin': u'wèn',           'type': 'verb',            'translation': 'to ask (a question)'},
    {'character': u'贵',     'pinyin': u'guì',           'type': 'adjective',            'translation': 'honorable; expensive'},
    {'character': u'姓',     'pinyin': u'xìng',          'type': 'verb/noun',            'translation': '(one’s) surname is...; to be surnamed; surname'},
    {'character': u'我',     'pinyin': u'wǒ',            'type': 'pronoun',            'translation': 'I; me'},
    {'character': u'呢',     'pinyin': u'ne',            'type': 'question particle',            'translation': '(question particle)'},
    {'character': u'小姐',   'pinyin': u'xiǎojie',       'type': 'noun',            'translation': ' Miss; young lady'},
    {'character': u'叫',     'pinyin': u'jiào',          'type': 'verb',            'translation': 'to be called; to call'},
    {'character': u'什么',   'pinyin': u'shénme',         'type': 'question pronoun',            'translation': 'what'}, 
    {'character': u'名字',   'pinyin': u'míngzi',         'type': 'noun',            'translation': 'name'},
    {'character': u'先生',   'pinyin': u'xiānsheng',      'type': 'noun',            'translation': 'Mr.; husband; teacher'},
    {'character': u'李友',   'pinyin': u'lǐ yǒu',         'type': '--',            'translation': '(a personal name)'},
    {'character': u'李',     'pinyin': u'lǐ',            'type': '--',            'translation': '(a surname); plum'},
    {'character': u'王朋',   'pinyin': u'wáng péng',     'type': '--',            'translation': '(a personal name)'},
    {'character': u'王',     'pinyin': u'wáng',          'type': '--',            'translation': '(a surname); king'},

    # Page 28
    {'character': u'是 ' ,     'pinyin': u'shì',         'type': 'verb',           'translation': 'to be '},
    {'character': u'老师',     'pinyin': u'lǎoshī',       'type': 'noun',            'translation': 'teacher'},  
    {'character': u'吗 ' ,     'pinyin': u'mǎ',          'type': 'question particle',            'translation': '(question particle)'},
    {'character': u'不 ' ,     'pinyin': u'bù',          'type': 'adverb',            'translation': 'not; no'},
    {'character': u'学生',     'pinyin': u'xuésheng',     'type': 'noun',             'translation': 'student '},
    {'character': u'也 ' ,     'pinyin': u'yě',          'type': 'adverb',            'translation': 'too; also'},
    {'character': u'人 ' ,     'pinyin': u'rén',         'type': 'noun',            'translation': 'people; person'},
    {'character': u'中国',     'pinyin': u'zhōngguó',    'type': '--',             'translation': 'China'},
    {'character': u'北京',     'pinyin': u'běijīng',      'type': '--',             'translation': 'Beijing'},
    {'character': u'美国',     'pinyin': u'měiguó',       'type': '--',            'translation': 'America '},
    {'character': u'纽约',     'pinyin': u'niǔyuē',       'type': '--',            'translation': 'New York'},

    #page 43
    {'character': u'那 ',      'pinyin':u'nā',           'type': 'pronoun',           'translation': 'that'},
    {'character': u'的 ' ,     'pinyin':u'de',           'type': 'particle',           'translation': '(a possessive or descriptive particle)'},
    {'character': u'照片',      'pinyin':u'zhàopiàn',     'type': 'noun',            'translation': 'picture; photo'},
    {'character': u'这 ' ,     'pinyin':u'zhè',          'type': 'pronoun',           'translation': 'this'},
    {'character': u'爸爸',      'pinyin':u'bàba',         'type': 'noun',            'translation': 'father, dad'},
    {'character': u'妈妈',      'pinyin':u'māma',         'type': 'noun',            'translation': 'mother, mom'},
    {'character': u'个 ',      'pinyin':u'gè',            'type': 'measure word',           'translation': '(measure word for many common everyday objects)'},
    {'character': u'女 ',      'pinyin':u'nǚ',           'type': 'adjective',           'translation': 'female'},
    {'character': u'孩子',     'pinyin':u'háizi',         'type': 'noun',            'translation': 'child'},
    {'character': u'谁 ' ,     'pinyin':u'shéi',         'type': 'question pronoun',            'translation': 'who'},
    {'character': u'他 ' ,     'pinyin':u'tā',           'type': 'pronoun',           'translation': 'she; her'},
    {'character': u'姐姐',     'pinyin':u'jiějie',        'type': 'noun',             'translation': 'older sister'},
    {'character': u'男 ' ,     'pinyin':u'nán',          'type': 'adjective',           'translation': 'male'},
    {'character': u'弟弟',     'pinyin':u'dìdi',          'type': 'noun',            'translation': 'younger brother'},
    {'character': u'他 ' ,     'pinyin':u'tā',           'type': 'pronoun',           'translation': 'he; him'},
    {'character': u'大哥',     'pinyin':u'dàgē',          'type': 'noun',             'translation': 'eldest brother'},
    {'character': u'儿子',     'pinyin':u'érzi',          'type': 'noun',             'translation': 'son'},
    {'character': u'有 ' ,     'pinyin':u'yǒu',           'type': 'verb',            'translation': 'to have; to exist'},
    {'character': u'女儿',     'pinyin':u'nǚér',          'type': 'noun',             'translation': 'daughter'},
    {'character': u'没 ' ,     'pinyin':u'méi',           'type': 'adverb',             'translation': 'not'},
    {'character': u'高文中',   'pinyin':u'gāowénzhōng',    'type': '--',            'translation': '(a personal name)'},
    {'character': u'高 ' ,     'pinyin':u'gāo',           'type': '--',            'translation': '(a surname), tall; high'},

    # page 51
    {'character': u'家 ',         'pinyin': u'jiā',          'type': 'noun',      'translation': 'family; home'},
    {'character': u'几 ',         'pinyin': u'jī',           'type': 'numerical',          'translation': 'how many; some; a few'},
    {'character': u'口 ',         'pinyin': u'kǒu',          'type': 'measure word',        'translation': '(measure word for number of family members)'},
    {'character': u'哥哥',        'pinyin': u'gēge',          'type': 'noun',       'translation': 'older brother'},
    {'character': u'两 ',         'pinyin': u'liǎng',        'type': 'numerical',      'translation': 'two; a couple of'},
    {'character': u'妹妹',        'pinyin': u'mèimei',        'type': 'noun',       'translation': 'younger sister'},
    {'character': u'和 ',         'pinyin': u'hé',           'type': 'conjunction',      'translation': 'and '},
    {'character': u'大姐',        'pinyin': u'dàjiě',         'type': 'noun',       'translation': 'eldest sister'},
    {'character': u'二姐',        'pinyin': u'èrjiě',         'type': 'noun',       'translation': 'second oldest sister  '},
    {'character': u'做 ',         'pinyin': u'zuò',          'type': 'verb',       'translation': 'todo '},
    {'character': u'工作',        'pinyin': u'gōngzuò',       'type': 'noun/verb',       'translation': 'job; to work'},
    {'character': u'律师',        'pinyin': u'lǜshī',         'type': 'noun',       'translation': 'lawyer'},
    {'character': u'英文',        'pinyin': u'yīngwén',       'type': 'noun',        'translation': 'English (language)'},
    {'character': u'都 ' ,        'pinyin': u'dōu',          'type': 'adverb',       'translation': 'both; all'},
    {'character': u'大学生',      'pinyin': u'dàxuéshēng',    'type': 'noun',       'translation': 'college student'},
    {'character': u'大学',        'pinyin': u'dàxué',         'type': 'noun',        'translation': 'university; college'},
    {'character': u'医生',        'pinyin': u'yīshēng',       'type': 'noun',        'translation': 'doctor, physician'},
    {'character': u'白英爱',       'pinyin': u'bái yīng ài',   'type': '--',       'translation': '(a personal name)'},

    # Page 68
    {'character': u'九月',   'pinyin': u'jiǔyuè',           'type': 'noun',      'translation': 'September'},
    {'character': u'月 ',    'pinyin': u'yuè',              'type': 'noun',     'translation': 'month'},
    {'character': u'十二',   'pinyin': u'shíèr',            'type': 'numerical',      'translation': 'twelve'},
    {'character': u'号 ' ,   'pinyin': u'háo',              'type': 'measure word',     'translation': '(measure word for number in a series; day of the month)'},
    {'character': u'星期',    'pinyin': u'xīngqī',          'type': 'noun',     'translation': 'week'},
    {'character': u'星期四',  'pinyin': u'xīngqīsì',        'type': 'noun',     'translation': 'Thursday'},
    {'character': u'天 ',    'pinyin': u'tiān',            'type': 'noun',     'translation': 'day'},
    {'character': u'生日',   'pinyin': u'shēngrì',          'type': 'noun',     'translation': 'birthday'},
    {'character': u'生 ',    'pinyin': u'shēng',           'type': 'verb',     'translation': 'to give birth to; to be born'},
    {'character': u'日 ',    'pinyin': u'rì',              'type': 'noun',     'translation': 'day; sun'},
    {'character': u'今年',   'pinyin': u'jīnnián',         'type': 'time word',     'translation': 'this year'},
    {'character': u'年 ',    'pinyin': u'nián',            'type': 'noun',     'translation': 'year'},
    {'character': u'多 ',    'pinyin': u'duō',             'type': 'adverb',     'translation': 'how many/much; to what extent; many'},
    {'character': u'大 ',    'pinyin': u'dà',              'type': 'adjective',     'translation': 'big; old'},
    {'character': u'十八',   'pinyin': u'shíbā',           'type': 'numerical',     'translation': 'eighteen'},
    {'character': u'岁 ',    'pinyin': u'suì',             'type': 'noun',     'translation': 'year (of age)'},
    {'character': u'吃 ',    'pinyin': u'chī',             'type': 'verb',     'translation': 'to eat'},
    {'character': u'饭 ',    'pinyin': u'fàn',             'type': 'noun',     'translation': 'meal; (cooked) rice'},
    {'character': u'怎么样',  'pinyin': u'zěnmeyàng',       'type': 'question pronoun',     'translation': 'Is it O.K.? How is that? How does that sound?'},
    {'character': u'太了',   'pinyin': u'tài..le',          'type': '--',    'translation': 'too; extremely'},
    {'character': u'谢谢',   'pinyin': u'xièxie',           'type': 'verb',    'translation': 'to thank'},
    {'character': u'喜欢',   'pinyin': u'xǐhuan',           'type': 'verb',    'translation': 'to like '},
    {'character': u'蔡 ',    'pinyin': u'cài',              'type': 'noun',    'translation': 'dishes, cuisine'},
    {'character': u'还是',   'pinyin': u'háishi',           'type': 'conjunction',    'translation': 'or '},
    {'character': u'可是',   'pinyin': u'kěshì',            'type': 'conjunction',    'translation': 'but '},
    {'character': u'我们',   'pinyin': u'wǒmen',            'type': 'pronoun',    'translation': 'we '},
    {'character': u'点 ',    'pinyin': u'diǎn',             'type': 'measure word',    'translation': 'o’clock (lit. dot, point, thus “points on the clock”)'},
    {'character': u'半 ',    'pinyin': u'bàn',              'type': 'numerical',    'translation': 'half; half an hour'},
    {'character': u'晚上',   'pinyin': u'wǎnshang',         'type': 'timeword/noun',    'translation': 'evening; night'},
    {'character': u'见 ',    'pinyin': u'jiàn',             'type': 'verb',    'translation': 'to see '},
    {'character': u'再见',   'pinyin': u'zàijiàn',          'type': 'verb',    'translation': 'goodbye; see you '},
    {'character': u'再 ',    'pinyin': u'zài',              'type': 'adverb',    'translation': 'again '},
    {'character': u'英国',   'pinyin': u'yīngguó',          'type': '--',    'translation': 'Britain; England'},

    # Chapter 3: Dates and Times
    # Page 85
    {'character': u'现在 ',      'pinyin': u'xiànzài',      'type': 'time word',    'translation': 'now'},
    {'character': u'刻  ',      'pinyin': u'kè',            'type': 'measure word',    'translation': 'quarter(of an hour)'},
    {'character': u'事  ',      'pinyin': u'shì',           'type': 'noun',    'translation': 'matter; affair; event'},
    {'character': u'今天 ',      'pinyin': u'jīntiān',       'type': 'time word',   'translation': 'today '},
    {'character': u'很  ',      'pinyin': u'hěn',            'type': 'adverb',    'translation': 'very'},
    {'character': u'忙  ',      'pinyin': u'máng',           'type': 'adjective',    'translation': 'very'},
    {'character': u'明天 ',      'pinyin': u'míngtiān',       'type': 'time word',   'translation': 'tomorrow'},
    {'character': u'晚饭 ',      'pinyin': u'wǎnfàn',         'type': 'noun',   'translation': 'dinner; supper'},
    {'character': u'为什么',     'pinyin': u'wèishénme',       'type': 'question pronoun',   'translation': 'why'},
    {'character': u'为  ',      'pinyin': u'wéi',             'type': 'prep',    'translation': 'for '},
    {'character': u'因为 ',      'pinyin': u'yīnwèi',         'type': 'conjunction',   'translation': 'because'},
    {'character': u'还  ',      'pinyin': u'hái',             'type': 'adverb',    'translation': 'also; too; as well'},
    {'character': u'同学 ',      'pinyin': u'tóngxué',        'type': 'noun',   'translation': 'classmate'},
    {'character': u'认识 ',      'pinyin': u'rènshi',        'type': 'verb',   'translation': 'to be acquainted with; to recognize'},
    {'character': u'朋友 ',      'pinyin': u'péngyou',       'type': 'noun',   'translation': 'friend'},

    # Chapter 4
    # Page 100
    {'character': u'周末',    'pinyin': u'zhōumò',        'type': 'noun',      'translation': 'weekend'},
    {'character': u'打球',    'pinyin': u'dǎ qiú',        'type': 'verb plus object',      'translation': 'to play ball'},
    {'character': u'打 ' ,   'pinyin': u'dá',            'type': 'verb',     'translation': 'to hit'},
    {'character': u'球 ' ,   'pinyin': u'qiú',           'type': 'noun',      'translation': 'ball '},
    {'character': u'看 ' ,   'pinyin': u'kān',           'type': 'verb',      'translation': 'to watch; to look; to read'},
    {'character': u'电视',    'pinyin': u'diànshì',       'type': 'noun',      'translation': 'television'},
    {'character': u'电 ' ,   'pinyin': u'diàn',          'type': 'noun',      'translation': 'electricity'},
    {'character': u'视 ' ,   'pinyin': u'shì',           'type': 'noun',      'translation': 'vision'},
    {'character': u'唱歌',    'pinyin': u'chàng gē',     'type': 'verb plus object',      'translation': 'to sing(a song) '},
    
    {'character': u'唱 ',    'pinyin': u'chàng',         'type': 'verb',   'translation': 'to sing'},
    {'character': u'歌 ',    'pinyin': u'gē',            'type': 'noun',   'translation': 'song '},
    {'character': u'跳舞',   'pinyin': u' tiàowǔ',        'type': 'verb plus object',  'translation': 'to dance'},
    {'character': u'跳 ',    'pinyin': u'tiào',          'type': 'verb',    'translation': 'to  jump'},
    {'character': u'舞 ',    'pinyin': u'wǔ',            'type': 'noun',    'translation': 'dance '},
    {'character': u'听 ',    'pinyin': u'tīng',          'type': 'verb',    'translation': 'to listen '},
    {'character': u'音乐',   'pinyin': u' yīnyuè',        'type': 'noun',  'translation': ' music'},
    {'character': u'书 ',    'pinyin': u'shū',            'type': 'noun',    'translation': 'book'},
    {'character': u'对 ',    'pinyin': u'duì',            'type': 'adjective',    'translation': 'right; correct'},
    {'character': u'有的',   'pinyin': u' yǒude',          'type': 'pronoun',  'translation': 'some '},
    {'character': u'时候',   'pinyin': u' shíhou',         'type': 'noun',  'translation': '(a point in) time; moment; (a duration of) time'},
    {'character': u'电影',   'pinyin': u' diànyǐng',       'type': 'noun',  'translation': 'movie'},
    {'character': u'影 ',    'pinyin': u'yǐng',           'type': 'noun',   'translation': 'shadow'},
    {'character': u'常常',   'pinyin': u' chángcháng',    'type': 'adverb',  'translation': 'often'},
    {'character': u'那 ',    'pinyin': u'nā',             'type': 'conjunction',   'translation': 'in that case; then'},
    {'character': u'去 ',    'pinyin': u'qù',             'type': 'verb',  'translation': 'to go '},
    {'character': u'外国',   'pinyin': u' wàiguó',        'type': 'noun',  'translation': 'foreign country'},
    {'character': u'请客',   'pinyin': u' qǐng kè',       'type': 'verb plus object',  'translation': 'to invite someone (to dinner, coffee, etc.); to play the host '},
    {'character': u'昨天',   'pinyin': u' zuótiān',       'type': 'time word',  'translation': 'yesterday'},
    {'character': u'所以',   'pinyin': u' suǒyǐ',         'type': 'conjunction',  'translation': 'so '},

    # Page 112
    {'character': u'小  ',   'pinyin': u'xiǎo',          'type': 'adjective',    'translation': 'small; little'},
    {'character': u'好久 ',   'pinyin': u'hǎojiǔ',        'type': 'a',    'translation': 'long time'},
    {'character': u'好  ',   'pinyin': u'hǎo',           'type': 'adverb',    'translation': 'very '},
    {'character': u'久  ',   'pinyin': u'jiǔ',           'type': 'adjective',    'translation': 'long(of time)'},
    {'character': u'不错 ',   'pinyin': u'bùcuò',         'type': 'adjective',     'translation': 'pretty good'},
    {'character': u'错  ',   'pinyin': u'cuò',           'type': 'adjective',    'translation': 'wrong '},
    {'character': u'想  ',   'pinyin': u'xiǎng',         'type': 'modal verb',    'translation': 'to want to; would like to; to think'},
    {'character': u'觉得 ',  'pinyin': u'juéde',          'type': 'verb',     'translation': 'to feel; to think'},
    {'character': u'有意思',  'pinyin': u'yǒu yìsi',       'type': 'adjective',       'translation': 'interesting'},
    {'character': u'意思 ',   'pinyin': u'yìsi',          'type': 'noun',     'translation': 'meaning'},
    {'character': u'只  ',   'pinyin': u'zhī',           'type': 'adverb',    'translation': 'only '},
    {'character': u'睡觉 ',   'pinyin': u'shuì jiào',    'type': 'verb plus object',      'translation': 'to sleep '}, 
    {'character': u'睡  ',   'pinyin': u'shuì',          'type': 'verb',    'translation': 'to sleep'},
    {'character': u'觉  ',   'pinyin': u'jiào',          'type': 'noun',    'translation': 'sleep '},
    {'character': u'算了 ',   'pinyin': u'suàn le',       'type': '--',    'translation': 'forget it; never mind'},
    {'character': u'找  ',   'pinyin': u'zhǎo',          'type': 'verb',    'translation': 'to look for '},
    {'character': u'别人 ',  'pinyin': u'biéren',         'type': 'noun',     'translation': 'other people; another person'},
    {'character': u'备的 ',   'pinyin': u'bèi (de)',      'type': 'adjective',   'translation': 'other'},

    # Chapter 5
    {'character': u'呀   ',  'pinyin': u'ya',            'type': 'particle',       'translation': '(interjectory particle used to soften a question)'},
    {'character': u'进   ',  'pinyin': u'jìn',           'type': 'verb',       'translation': 'to enter'},
    {'character': u'快   ',  'pinyin': u'kuài',          'type': 'adv/adj',    'translation': 'fast, quick; quickly'},
    {'character': u'进来  ', 'pinyin': u' jìn lái',       'type': 'verb plus complement',       'translation': 'to come in'},
    {'character': u'来   ',  'pinyin': u'lái',           'type': 'verb',      'translation': 'to come '},
    {'character': u'介绍  ', 'pinyin': u' jièshào',       'type': 'verb',    'translation': 'to introduce'},
    {'character': u'一下  ', 'pinyin': u' yī xià',        'type': 'n+m',    'translation': 'once; a bit'},
    {'character': u'高兴  ', 'pinyin': u' gāoxìng',       'type': 'adjective',    'translation': 'happy, pleased     '},
    {'character': u'漂亮  ', 'pinyin': u' piàoliang',     'type': 'adjective',   'translation': 'pretty'},
    {'character': u'坐   ',  'pinyin': u'zuò',            'type': 'verb',    'translation': 'to sit '},
    {'character': u'在   ',  'pinyin': u'zài',            'type': 'prep',     'translation': 'at; in; on'},
    {'character': u'那人  ', 'pinyin': u' nǎr',           'type': 'question pronoun',     'translation': 'where '},
    {'character': u'学校  ', 'pinyin': u' xuéxiào',       'type': 'noun',     'translation': 'school '},
    {'character': u'喝   ',  'pinyin': u'hē',             'type': 'verb',    'translation': 'to drink'},
    {'character': u'点   ',  'pinyin': u'diǎn(r)',        'type': 'measure word',    'translation': 'a little, a bit; some'},
    {'character': u'茶   ',  'pinyin': u'chá',            'type': 'noun',    'translation': 'tea '},
    {'character': u'咖啡  ', 'pinyin': u' kāfēi',         'type': 'noun',     'translation': 'coffee'},
    {'character': u'吧   ',  'pinyin': u'bā',             'type': 'particle',    'translation': '(a sentence-final particle)'},
    {'character': u'要   ',  'pinyin': u'yāo',            'type': 'verb',    'translation': 'to want'},
    {'character': u'瓶   ',  'pinyin': u'píng',           'type': ' measure word/noun',    'translation': '(measure word for bottles); bottle'},
    {'character': u'可乐  ', 'pinyin': u' kělè',          'type': 'noun',    'translation': '[Coke or Pepsi] cola'},
    {'character': u'可以  ', 'pinyin': u' kěyǐ',          'type': 'modal verb',    'translation': 'can; may'},
    {'character': u'对不起 ', 'pinyin': u' duìbuqǐ',       'type': 'verb',     'translation': 'sorry'},
    {'character': u'给   ',  'pinyin': u'gěi',            'type': 'verb',    'translation': 'to give '},
    {'character': u'被   ',  'pinyin': u'bèi',            'type': 'measure word',    'translation': '(measure word for cup and glass)'},
    {'character': u'水   ',  'pinyin': u'shuǐ',           'type': 'noun',    'translation': 'water'},
    {'character': u'高小音 ', 'pinyin': u'gāo xiǎoyīn',   'type': '--',     'translation': '(a personal name)'},

    # Page 136
    {'character': u'玩  ',   'pinyin': u'wán(r)',        'type': 'verb',     'translation': 'to have fun; to play              '},
    {'character': u'了  ',   'pinyin': u'le',            'type': 'particle',     'translation': '(a dynamic particle)'},
    {'character': u'图书馆',  'pinyin': u'túshūguǎn',     'type': 'noun',      'translation': 'library'},
    {'character': u'一起 ',  'pinyin': u'yīqǐ',           'type': 'adverb',      'translation': 'together '},
    {'character': u'聊天 ',  'pinyin': u'liáo tiān(r)',   'type': 'verb plus object',      'translation': 'to chat   '},
    {'character': u'聊  ',   'pinyin': u'liáo',           'type': 'verb',     'translation': 'to chat'},
    {'character': u'天  ',   'pinyin': u'tiān',           'type': 'noun',     'translation': 'sky '},
    {'character': u'才  ',   'pinyin': u'cái',            'type': 'adverb',     'translation': 'not until; only then'},
    {'character': u'回家 ',  'pinyin': u'huí jiā',        'type': 'verb plus object',      'translation': 'to go home   '},
    {'character': u'回  ',   'pinyin': u'huí',           'type': 'verb',     'translation': 'to return'},

    # Chapter 6 page 152
    {'character': u'给  ',    'pinyin': u'gěi',              'type': 'prep',     'translation': 'to; for'},
    {'character': u'打电话',   'pinyin': u'dǎ diànhuà',       'type': 'verb plus object',       'translation': 'to make a phone call'},
    {'character': u'电话 ',   'pinyin': u'diànhuà',           'type': 'noun',        'translation': 'telephone     '},
    {'character': u'喂  ',   'pinyin': u'wéi/wèi',           'type': 'interjection',    'translation': '(on telephone) Hello!; Hey!'},
    {'character': u'在  ',    'pinyin': u'zài',              'type': 'verb',        'translation': 'to be present; to be at (a place)'},
    {'character': u'就  ',    'pinyin': u'jiù',              'type': 'adverb',     'translation': 'precisely; exactly'},
    {'character': u'您  ',    'pinyin': u'nín',              'type': 'pronoun',      'translation': 'you(honorific)'},
    {'character': u'那  ',    'pinyin': u'nā/něi',           'type': 'question pronoun',      'translation': 'which'},
    {'character': u'位  ',    'pinyin': u'wèi',              'type': 'measure word',        'translation': '(polite measure word for people)'},
    {'character': u'下午 ',   'pinyin': u'xiàwǔ',             'type': 'time word',        'translation': 'afternoon '},
    {'character': u'时间 ',   'pinyin': u'shíjiān',           'type': 'noun',        'translation': 'time  '},
    {'character': u'问题 ',   'pinyin': u'wèntí',             'type': 'noun',        'translation': 'question; problem'},
    {'character': u'要  ',    'pinyin': u'yāo',               'type': 'modal verb',      'translation': 'will, be going to; to want to, to have a desire to'},
    {'character': u'开会 ',   'pinyin': u'kāi huì',           'type': 'verb plus object',     'translation':  'to have a meeting '},
    {'character': u'开  ',    'pinyin': u'kāi',               'type': 'verb',       'translation': 'to open; to hold (a meeting, party, etc.)'},
    {'character': u'会  ',    'pinyin': u'huì',               'type': 'noun',       'translation': 'meeting'},
    {'character': u'上午 ',   'pinyin': u'shàngwǔ',            'type': 'time word',       'translation': 'morning          '},
    {'character': u'节  ',    'pinyin': u'jiē',               'type': 'measure word',      'translation': '(measure word for class periods)'},
    {'character': u'棵  ',    'pinyin': u'kē',                'type': 'noun',      'translation': 'class; course; lesson'},
    {'character': u'年级 ',   'pinyin': u'niánjí',             'type': 'noun',      'translation': 'grade in school'},
    {'character': u'考试 ',   'pinyin': u'kǎo shì',            'type': 'verb plus object/noun',       'translation': 'to give or take a test; test '},
    {'character': u'考  ',    'pinyin': u'kǎo',                'type': 'verb',      'translation': 'to give or take a test'},
    {'character': u'试  ',    'pinyin': u'shì',                'type': 'noun/verb',      'translation': 'test; to try; to experiment'},
    {'character': u'以后 ',   'pinyin': u'yǐhòu',              'type': 'time word',     'translation': 'after; from now on, later on '},
    {'character': u'空  ',    'pinyin': u'kòng(r)',            'type': 'noun',      'translation': 'free time'},
    {'character': u'要是 ',   'pinyin': u'yàoshi',             'type': 'conjunction',   'translation': 'if '},
    {'character': u'方便 ',   'pinyin': u'fāngbiàn',           'type': 'adjective',     'translation': 'convenient '},
    {'character': u'到  ',    'pinyin': u'dào',                'type': 'verb',      'translation': 'to go to; to arrive'},
    {'character': u'办公室',  'pinyin': u'bàngōngshì',          'type': 'noun',       'translation': 'office '},
    {'character': u'行  ',    'pinyin': u'xíng',               'type': 'verb',      'translation': 'all right; O.K.'},
    {'character': u'等  ',    'pinyin': u'děng',               'type': 'verb',      'translation': 'to wait; to wait for '},
    {'character': u'别  ',    'pinyin': u'bié',                'type': 'adverb',    'translation': 'dont'},
    {'character': u'客气 ',    'pinyin': u'kèqi',               'type': 'adjective',   'translation': 'polite '},
    {'character': u'常老师',   'pinyin': u'cháng lǎoshī',       'type': ' --',    'translation': 'Teacher Chang   '},

    # Page 162
    {'character': u'下个',    'pinyin': u'xià gè',        'type': '--',      'translation': 'next one '},
    {'character': u'下 ',     'pinyin': u'xià',           'type': '--',     'translation': 'below; next'},
    {'character': u'中文',    'pinyin': u'zhōngwén',      'type': 'noun',        'translation': 'Chinese language'},
    {'character': u'文 ',    'pinyin': u'wén',            'type': 'noun',       'translation': 'language; script; written language'},
    {'character': u'帮 ',    'pinyin': u'bāng',           'type': 'verb',     'translation': 'to help'},
    {'character': u'准备',   'pinyin': u'zhǔnbèi',        'type': 'verb',    'translation': ' to prepare'},
    {'character': u'练习',   'pinyin': u'liànxí',         'type': 'verb',    'translation': ' to practice'},
    {'character': u'说 ',    'pinyin': u'shuō',           'type': 'verb',     'translation': 'to say, to speak'},
    {'character': u'啊 ',    'pinyin': u'a',              'type': 'particle',     'translation': '(a sentence-final particle of exclamation, interrogation, etc.)'},
    {'character': u'但是',   'pinyin': u'dànshì',         'type': 'conjunction',    'translation': 'but '},
    {'character': u'得 ',    'pinyin': u'déi',            'type': 'adverb',     'translation': 'must; to have to '},
    {'character': u'跟 ',    'pinyin': u'gēn',            'type': 'prep',     'translation': 'with '},
    {'character': u'见面',   'pinyin': u'jiàn miàn',      'type': 'verb plus object',     'translation': ' to meetup; to meet with '},
    {'character': u'面 ',    'pinyin': u'miàn',           'type': 'noun',     'translation': 'face '},
    {'character': u'回来',   'pinyin': u'huí lai',        'type': 'verb plus complement',     'translation': 'to come back'},
]

choice = random.randint(0,len(words) - 1)
# print choice

print '-'*40
print '   Integrated Chinese Word of the Day'
print '-'*40
print 'Characters: '  + words[choice]['character'].encode('utf-8')
print 'Pinyin: %s'      % words[choice]['pinyin'].encode('utf-8')
print 'Type: '        + words[choice]['type']
print 'Translation: ' + words[choice]['translation']
print '-'*40


